workflow:
    rules:
        -   if: '"merge_request_event" == $CI_PIPELINE_SOURCE'
            when: never
        -   when: always

variables:
    DOCKER_BUILDER_IMAGE: harbor.local.darkanakin41.com/base/gitlab-runner:latest

default:
    image: ${DOCKER_BUILDER_IMAGE}
    tags:
        - kubernetes
    before_script:
        - harbor-login
    interruptible: true
    cache:
        - &node_module_cache
            key: node_modules-$CI_COMMIT_REF_SLUG
            fallback_keys:
                - node_modules-$CI_DEFAULT_BRANCH
                - node_modules-default
            policy: pull
            paths:
                - node_modules/

install_node_modules:
    stage: install
    interruptible: false
    cache:
        - <<: *node_module_cache
          policy: pull-push
    script:
        - docker compose run --rm node npm install

    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "pipeline"
          when: never
        - changes:
              - package-lock.lock
        - when: manual
          allow_failure: true

stages:
    - install
    - test
    - build
