version: '3.4'

services:
    nginx:
        image: harbor.local.darkanakin41.com/react-components-library/storybook:latest
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        volumes:
            -   ./storybook-static:/srv/app/public
        ports:
            - 8080:80

    node:
        image: node:20.9.0-alpine
        volumes:
            - ./:/srv
        working_dir: /srv
