{{ $chartName := .Chart.Name }}
{{- range $host := .Values.ingress.hosts }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: {{ $chartName }}
    annotations:
        gethomepage.dev/description: My react component library
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/group: Dev
        gethomepage.dev/href: {{ $host }}
        gethomepage.dev/name: {{ $chartName }}
        gethomepage.dev/pod-selector: app.kubernetes.io/instance={{ $chartName }}-storybook,pod.lifecycle in (permanent)

spec:
    entryPoints:
        - websecure
    routes:
        - kind: Rule
          match: Host(`{{ $host }}`)
          services:
              - name: {{ $chartName }}-storybook
                port: 8080
{{- end }}
