---
apiVersion: v1
kind: Service
metadata:
    name: "{{ .Chart.Name }}-storybook"
spec:
    type: ClusterIP
    ports:
        - name: http
          port: 80
          targetPort: 80
    selector:
        app: "{{ .Chart.Name }}-storybook"
