storybook:build:
    stage: build
    cache:
        - key: node_modules-$CI_COMMIT_REF_SLUG
          fallback_keys:
              - node_modules-$CI_DEFAULT_BRANCH
              - node_modules-default
          policy: pull
          paths:
              - node_modules/
    artifacts:
        paths:
            - storybook-static/
    script:
        - docker compose run --rm node npm run build

storybook:docker:
    stage: build
    image: harbor.local.darkanakin41.com/base/gitlab-runner:latest
    cache:
        - key: node_modules-$CI_COMMIT_REF_SLUG
          fallback_keys:
              - node_modules-$CI_DEFAULT_BRANCH
              - node_modules-default
          policy: pull
          paths:
              - node_modules/
    needs:
        - job: storybook:build
          artifacts: true
          optional: false
    script:
        - docker compose build nginx
        - docker compose
